name: Java CI with Maven

on:
  push:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest

    continue-on-error: ${{ github.event_name == 'push' }}

    steps:
    - uses: actions/checkout@v4
    - name: Configurar JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Ejecutar tests con Maven
      run: mvn test

    - name: Crear directorio de reportes si no existe
      run: mkdir -p target/surefire-reports/

    - name: Publicar reporte de tests
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: junit-test-results
        path: target/surefire-reports/
